//
// Created by Ivan on 11/17/2021.
//

#ifndef BULLSANDCOWS_CONSTANTS_H
#define BULLSANDCOWS_CONSTANTS_H

enum Constants{
    ASCII_CODE_OF_SMALL_A = 97,
    ASCII_CODE_OF_ZERO = 48,
    ASCII_CODE_OF_NINE = 57,
    ASCII_CODE_OF_SMALL_Z = 122,
    MAX_AMOUNT_OF_POSSIBLE_SYMBOLS = 36,
    NUMBER_TO_APPEAR_BETWEEN_A_AND_Z = 25,
    NUMBER_TO_APPEAR_BETWEEN_ZERO_AND_NINE = 35
};

#endif //BULLSANDCOWS_CONSTANTS_H
